apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client-deployment
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - name: web-client
          image: gchen63/web-client-poc4:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-client-service
spec:
  selector:
    app: web-client
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
