name: Docker Image and Publish HTML page RC

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Login DockerHub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build -t web-client-poc4 ./client

    - name: Tag Docker image for the push
      run: docker tag web-client-poc4:latest ${{ secrets.DOCKER_USER }}/web-client-poc4
      
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USER }}/web-client-poc4
