name: Docker Image and Publish of Web Server RC

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Login DockerHub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build -t web-server-poc4 .

    - name: Tag Docker image for the push
      run: docker tag web-server-poc4:latest ${{ secrets.DOCKER_USER }}/web-server-poc4
      
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USER }}/web-server-poc4
